#Definimos el tipo de base de datos
quarkus.datasource.db-kind=postgresql
#Usuario que conecta a la base de datos
quarkus.datasource.username=postgres
#password del usurio de conexion
quarkus.datasource.password=contra12345
#URL de conexion a la base de datos
quarkus.datasource.jdbc.url=jdbc:postgresql://localhost:5432/pa2db
#Parametros recomendables
##Sincroniza el codigo con la base de datos
quarkus.hibernate-orm.database.generation=update
##Se muestra en la consola de quarkus
quarkus.hibernate-orm.log.sql=true